import re

with open('/Users/chloedreamer/chloe-workspace/src/lib/quotes.ts', 'r', encoding='utf-8') as f:
    content = f.read()

# Map of (no-diacritics vi text) -> (with-diacritics vi text)
# We'll match each vi: "..." and replace with the correct diacritical version
replacements = {
    # Napoleon Hill — Think and Grow Rich (1-28)
    'Bat cu dieu gi tri oc co the hinh dung va tin tuong, no deu co the dat duoc.': 'Bất cứ điều gì trí óc có thể hình dung và tin tưởng, nó đều có thể đạt được.',
    'Khoi dau cua moi thanh tuu chinh la khat vong.': 'Khởi đầu của mọi thành tựu chính là khát vọng.',
    'Suc manh va su truong thanh chi den tu no luc va phan dau khong ngung.': 'Sức mạnh và sự trưởng thành chỉ đến từ nỗ lực và phấn đấu không ngừng.',
    'Moi nghich canh, moi that bai, moi noi dau deu mang trong no hat giong cua mot loi ich tuong duong hoac lon hon.': 'Mọi nghịch cảnh, mọi thất bại, mọi nỗi đau đều mang trong nó hạt giống của một lợi ích tương đương hoặc lớn hơn.',
    'Hay dat tam tri vao mot muc tieu ro rang va quan sat the gioi nhanh chong nhuong duong cho ban.': 'Hãy đặt tâm trí vào một mục tiêu rõ ràng và quan sát thế giới nhanh chóng nhường đường cho bạn.',
    'Nguoi bo cuoc khong bao gio chien thang, nguoi chien thang khong bao gio bo cuoc.': 'Người bỏ cuộc không bao giờ chiến thắng, người chiến thắng không bao giờ bỏ cuộc.',
    'Ban la chu nhan so phan minh. Ban co the tac dong, dinh huong va kiem soat moi truong xung quanh.': 'Bạn là chủ nhân số phận mình. Bạn có thể tác động, định hướng và kiểm soát môi trường xung quanh.',
    'Khat vong la khoi nguon cua moi thanh tuu, khong phai hy vong, khong phai uoc muon, ma la mot khat khao chay bong vuot len tren tat ca.': 'Khát vọng là khởi nguồn của mọi thành tựu, không phải hy vọng, không phải ước muốn, mà là một khát khao cháy bỏng vượt lên trên tất cả.',
    'Khi that bai den, hay chap nhan no nhu tin hieu rang ke hoach cua ban chua vung, xay dung lai va tiep tuc huong toi muc tieu.': 'Khi thất bại đến, hãy chấp nhận nó như tín hiệu rằng kế hoạch của bạn chưa vững, xây dựng lại và tiếp tục hướng tới mục tiêu.',
    'Kien nhan, kien tri va mo hoi tao nen su ket hop bat bai cho thanh cong.': 'Kiên nhẫn, kiên trì và mồ hôi tạo nên sự kết hợp bất bại cho thành công.',
    'Neu ban khong chinh phuc ban than, ban se bi chinh ban than chinh phuc.': 'Nếu bạn không chinh phục bản thân, bạn sẽ bị chính bản thân chinh phục.',
    'Nguoi lam nhieu hon so voi nhung gi duoc tra cong se som duoc tra cong nhieu hon so voi nhung gi anh ta lam.': 'Người làm nhiều hơn so với những gì được trả công sẽ sớm được trả công nhiều hơn so với những gì anh ta làm.',
    'Thanh tuu lon thuong sinh ra tu su hy sinh lon, va khong bao gio la ket qua cua su ich ky.': 'Thành tựu lớn thường sinh ra từ sự hy sinh lớn, và không bao giờ là kết quả của sự ích kỷ.',
    'Hay suy nghi ky truoc khi noi, vi loi noi va anh huong cua ban se gieo hat giong thanh cong hoac that bai trong tam tri nguoi khac.': 'Hãy suy nghĩ kỹ trước khi nói, vì lời nói và ảnh hưởng của bạn sẽ gieo hạt giống thành công hoặc thất bại trong tâm trí người khác.',
    'Hanh dong moi la thuoc do thuc su cua tri thong minh.': 'Hành động mới là thước đo thực sự của trí thông minh.',
    'The gioi co thoi quen nhuong cho cho nguoi ma hanh dong cho thay ho biet minh dang di dau.': 'Thế giới có thói quen nhường chỗ cho người mà hành động cho thấy họ biết mình đang đi đâu.',
    'Co hoi lon cua ban co the ngay tai noi ban dang dung.': 'Cơ hội lớn của bạn có thể ngay tại nơi bạn đang đứng.',
    'Khong ai san sang cho dieu gi cho den khi ho tin rang minh co the dat duoc no.': 'Không ai sẵn sàng cho điều gì cho đến khi họ tin rằng mình có thể đạt được nó.',
    'Moi nguoi chien thang trong bat ky cong viec nao deu phai san sang dot tau va cat moi duong lui.': 'Mọi người chiến thắng trong bất kỳ công việc nào đều phải sẵn sàng đốt tàu và cắt mọi đường lui.',
    'Hay tran trong tam nhin va uoc mo cua ban vi chung la nhung dua con cua tam hon, la ban thiet ke cho thanh tuu cuoi cung.': 'Hãy trân trọng tầm nhìn và ước mơ của bạn vì chúng là những đứa con của tâm hồn, là bản thiết kế cho thành tựu cuối cùng.',
    'Mot trong nhung nguyen nhan that bai pho bien nhat la thoi quen bo cuoc khi gap that bai tam thoi.': 'Một trong những nguyên nhân thất bại phổ biến nhất là thói quen bỏ cuộc khi gặp thất bại tạm thời.',
    'Muc tieu la giac mo co thoi han.': 'Mục tiêu là giấc mơ có thời hạn.',
    'Da so nguoi that bai vi thieu kien tri trong viec tao ke hoach moi thay the nhung ke hoach da that bai.': 'Đa số người thất bại vì thiếu kiên trì trong việc tạo kế hoạch mới thay thế những kế hoạch đã thất bại.',
    'Truoc khi thanh cong den trong cuoc doi, chac chan ban se gap nhieu that bai tam thoi.': 'Trước khi thành công đến trong cuộc đời, chắc chắn bạn sẽ gặp nhiều thất bại tạm thời.',
    'Nguoi co hoc khong nhat thiet la nguoi co nhieu kien thuc. Nguoi co hoc la nguoi da phat trien nang luc tri tue de co the dat duoc bat cu dieu gi ho muon.': 'Người có học không nhất thiết là người có nhiều kiến thức. Người có học là người đã phát triển năng lực trí tuệ để có thể đạt được bất cứ điều gì họ muốn.',
    'Y tuong la diem khoi dau cua moi tai san.': 'Ý tưởng là điểm khởi đầu của mọi tài sản.',
    'Dung cho doi; thoi diem hoan hao se khong bao gio den.': 'Đừng chờ đợi; thời điểm hoàn hảo sẽ không bao giờ đến.',
    'Nhieu vang da duoc khai thac tu suy nghi con nguoi hon la tu long dat.': 'Nhiều vàng đã được khai thác từ suy nghĩ con người hơn là từ lòng đất.',

    # Stephen Covey — 7 Habits (29-55)
    'Hay bat dau voi dich den trong tam tri.': 'Hãy bắt đầu với đích đến trong tâm trí.',
    'Dieu quan trong khong phai la uu tien nhung gi trong lich trinh, ma la len lich cho nhung uu tien cua ban.': 'Điều quan trọng không phải là ưu tiên những gì trong lịch trình, mà là lên lịch cho những ưu tiên của bạn.',
    'Hau het moi nguoi khong lang nghe de hieu, ho lang nghe de dap tra.': 'Hầu hết mọi người không lắng nghe để hiểu, họ lắng nghe để đáp trả.',
    'Hay tim hieu truoc, roi moi tim cach duoc hieu.': 'Hãy tìm hiểu trước, rồi mới tìm cách được hiểu.',
    'Gieo suy nghi, gat hanh dong; gieo hanh dong, gat thoi quen; gieo thoi quen, gat tinh cach; gieo tinh cach, gat so phan.': 'Gieo suy nghĩ, gặt hành động; gieo hành động, gặt thói quen; gieo thói quen, gặt tính cách; gieo tính cách, gặt số phận.',
    'Chung ta nhin the gioi khong nhu no von la, ma nhu chinh chung ta — hoac nhu cach ta duoc dinh hinh de nhin.': 'Chúng ta nhìn thế giới không như nó vốn là, mà như chính chúng ta — hoặc như cách ta được định hình để nhìn.',
    'De thay doi ban than hieu qua, truoc tien chung ta phai thay doi nhan thuc.': 'Để thay đổi bản thân hiệu quả, trước tiên chúng ta phải thay đổi nhận thức.',
    'Toi khong phai san pham cua hoan canh. Toi la san pham cua nhung quyet dinh cua minh.': 'Tôi không phải sản phẩm của hoàn cảnh. Tôi là sản phẩm của những quyết định của mình.',
    'Thoi quen la giao diem cua kien thuc, ky nang va khat vong.': 'Thói quen là giao điểm của kiến thức, kỹ năng và khát vọng.',
    'Hay song bang tri tuong tuong, khong phai bang qua khu.': 'Hãy sống bằng trí tưởng tượng, không phải bằng quá khứ.',
    'Hay chu dong. Giua kich thich va phan ung co mot khoang trong. Trong khoang trong do la quyen lua chon phan ung cua chung ta.': 'Hãy chủ động. Giữa kích thích và phản ứng có một khoảng trống. Trong khoảng trống đó là quyền lựa chọn phản ứng của chúng ta.',
    'Bat dau voi dich den trong tam tri. Neu ban can nhac ky dieu ban muon nguoi ta noi ve minh trong le tang, ban se tim thay dinh nghia thanh cong cua minh.': 'Bắt đầu với đích đến trong tâm trí. Nếu bạn cân nhắc kỹ điều bạn muốn người ta nói về mình trong lễ tang, bạn sẽ tìm thấy định nghĩa thành công của mình.',
    'Uu tien viec quan trong truoc. Dieu chinh la giu cho dieu chinh luon la dieu chinh.': 'Ưu tiên việc quan trọng trước. Điều chính là giữ cho điều chính luôn là điều chính.',
    'Hay nghi doi ben cung thang. Khong phai cach cua ban hay cach cua toi, ma la cach tot hon, cach cao hon.': 'Hãy nghĩ đôi bên cùng thắng. Không phải cách của bạn hay cách của tôi, mà là cách tốt hơn, cách cao hơn.',
    'Mai sac luoi cua. Dung bao gio ban ron cua den noi khong co thoi gian mai luoi cua.': 'Mài sắc lưỡi cưa. Đừng bao giờ bận rộn cưa đến nỗi không có thời gian mài lưỡi cưa.',
    'Cach chung ta nhin van de chinh la van de.': 'Cách chúng ta nhìn vấn đề chính là vấn đề.',
    'Niem tin la chat keo cua cuoc song. No la thanh phan thiet yeu nhat trong giao tiep hieu qua va la nen tang giu vung moi moi quan he.': 'Niềm tin là chất keo của cuộc sống. Nó là thành phần thiết yếu nhất trong giao tiếp hiệu quả và là nền tảng giữ vững mọi mối quan hệ.',
    'Lanh dao hieu qua la dat viec quan trong len truoc. Quan ly hieu qua la ky luat, la thuc thi.': 'Lãnh đạo hiệu quả là đặt việc quan trọng lên trước. Quản lý hiệu quả là kỷ luật, là thực thi.',
    'Neu toi thuc su muon cai thien tinh huong, toi co the lam viec tren dieu duy nhat toi kiem soat duoc — chinh minh.': 'Nếu tôi thực sự muốn cải thiện tình huống, tôi có thể làm việc trên điều duy nhất tôi kiểm soát được — chính mình.',
    'Khong phai dieu xay ra voi chung ta, ma la cach chung ta phan ung moi lam ton thuong chung ta.': 'Không phải điều xảy ra với chúng ta, mà là cách chúng ta phản ứng mới làm tổn thương chúng ta.',
    'Moi nguoi deu co bon nang luc: tu nhan thuc, luong tam, y chi doc lap va tri tuong tuong sang tao.': 'Mọi người đều có bốn năng lực: tự nhận thức, lương tâm, ý chí độc lập và trí tưởng tượng sáng tạo.',
    'Suc manh nam o su khac biet, khong phai su tuong dong.': 'Sức mạnh nằm ở sự khác biệt, không phải sự tương đồng.',
    'Giua nhung kho khan an chua co hoi.': 'Giữa những khó khăn ẩn chứa cơ hội.',
    'Cang bien minh cho su gian doi, no cang tro thanh van hoa thieu trung thuc. Va dieu do co the tro thanh vong xoay di xuong.': 'Càng biện minh cho sự gian dối, nó càng trở thành văn hóa thiếu trung thực. Và điều đó có thể trở thành vòng xoáy đi xuống.',
    'Chung ta khong phai con nguoi tren hanh trinh tam linh. Chung ta la linh hon tren hanh trinh lam nguoi.': 'Chúng ta không phải con người trên hành trình tâm linh. Chúng ta là linh hồn trên hành trình làm người.',
    'Con nguoi khong the song voi su thay doi neu khong co mot loi bat bien ben trong.': 'Con người không thể sống với sự thay đổi nếu không có một lõi bất biến bên trong.',
    'Tinh than chiu trach nhiem sinh ra kha nang ung pho.': 'Tinh thần chịu trách nhiệm sinh ra khả năng ứng phó.',

    # Atomic Habits — James Clear (56-100)
    'Ban khong vuon len tam muc tieu. Ban roi xuong tam he thong cua minh.': 'Bạn không vươn lên tầm mục tiêu. Bạn rơi xuống tầm hệ thống của mình.',
    'Moi hanh dong ban lam la mot phieu bau cho kieu nguoi ban muon tro thanh.': 'Mọi hành động bạn làm là một phiếu bầu cho kiểu người bạn muốn trở thành.',
    'Thoi quen la lai kep cua su tu hoan thien.': 'Thói quen là lãi kép của sự tự hoàn thiện.',
    'Cach hieu qua nhat de thay doi thoi quen la tap trung vao nguoi ban muon tro thanh, khong phai dieu ban muon dat duoc.': 'Cách hiệu quả nhất để thay đổi thói quen là tập trung vào người bạn muốn trở thành, không phải điều bạn muốn đạt được.',
    'Hay la nguoi thiet ke the gioi cua ban, khong chi la nguoi tieu thu no.': 'Hãy là người thiết kế thế giới của bạn, không chỉ là người tiêu thụ nó.',
    'Tot hon 1 phan tram moi ngay se tao nen su khac biet lon ve lau dai.': 'Tốt hơn 1 phần trăm mỗi ngày sẽ tạo nên sự khác biệt lớn về lâu dài.',
    'Thoi gian phong dai khoang cach giua thanh cong va that bai. No se nhan len bat cu dieu gi ban nuoi duong.': 'Thời gian phóng đại khoảng cách giữa thành công và thất bại. Nó sẽ nhân lên bất cứ điều gì bạn nuôi dưỡng.',
    'Moi dieu lon lao deu bat dau tu nhung dieu nho be. Hat giong cua moi thoi quen la mot quyet dinh nho.': 'Mọi điều lớn lao đều bắt đầu từ những điều nhỏ bé. Hạt giống của mọi thói quen là một quyết định nhỏ.',
    'Bo mot thoi quen xau giong nhu nho goc cay soi trong ta. Xay dung thoi quen tot giong nhu cham soc mot bong hoa mong manh moi ngay.': 'Bỏ một thói quen xấu giống như nhổ gốc cây sồi trong ta. Xây dựng thói quen tốt giống như chăm sóc một bông hoa mong manh mỗi ngày.',
    'Ban nen quan tam den quy dao hien tai hon la ket qua hien tai.': 'Bạn nên quan tâm đến quỹ đạo hiện tại hơn là kết quả hiện tại.',
    'Khi ban yeu qua trinh thay vi ket qua, ban khong can cho phep minh duoc hanh phuc.': 'Khi bạn yêu quá trình thay vì kết quả, bạn không cần cho phép mình được hạnh phúc.',
    'Muc tieu tot de dinh huong, nhung he thong moi la cach tot nhat de tien bo.': 'Mục tiêu tốt để định hướng, nhưng hệ thống mới là cách tốt nhất để tiến bộ.',
    'Thanh cong la san pham cua thoi quen hang ngay — khong phai nhung thay doi nghin nam mot lan.': 'Thành công là sản phẩm của thói quen hàng ngày — không phải những thay đổi nghìn năm một lần.',
    'Muc dich cua dat muc tieu la thang cuoc choi. Muc dich cua xay dung he thong la tiep tuc choi.': 'Mục đích của đặt mục tiêu là thắng cuộc chơi. Mục đích của xây dựng hệ thống là tiếp tục chơi.',
    'Nguoi chuyen nghiep bam sat lich trinh; nguoi nghiep du de cuoc song can tro.': 'Người chuyên nghiệp bám sát lịch trình; người nghiệp dư để cuộc sống cản trở.',
    'Ban khong phai la nan nhan cua moi truong. Ban cung co the la kien truc su cua no.': 'Bạn không phải là nạn nhân của môi trường. Bạn cũng có thể là kiến trúc sư của nó.',
    'Nhung khoanh khac quyet dinh thiet lap cac lua chon cho ban trong tuong lai.': 'Những khoảnh khắc quyết định thiết lập các lựa chọn cho bạn trong tương lai.',
    'Thay doi hanh vi that su la thay doi ban sac. Ban co the bat dau thoi quen vi dong luc, nhung ly do duy nhat ban duy tri la vi no tro thanh mot phan con nguoi ban.': 'Thay đổi hành vi thật sự là thay đổi bản sắc. Bạn có thể bắt đầu thói quen vì động lực, nhưng lý do duy nhất bạn duy trì là vì nó trở thành một phần con người bạn.',
    'Moi con them muon deu lien ket voi mong muon thay doi trang thai ben trong.': 'Mọi cơn thèm muốn đều liên kết với mong muốn thay đổi trạng thái bên trong.',
    'Bo lo mot lan la tai nan. Bo lo hai lan la bat dau mot thoi quen moi.': 'Bỏ lỡ một lần là tai nạn. Bỏ lỡ hai lần là bắt đầu một thói quen mới.',
    'Sai lam dau tien khong bao gio pha huy ban. Chinh vong xoay cua nhung sai lam lap lai moi la thu pha huy.': 'Sai lầm đầu tiên không bao giờ phá hủy bạn. Chính vòng xoáy của những sai lầm lặp lại mới là thứ phá hủy.',
    'Khi khong co gi co ve hieu qua, hay nhin nguoi tho da dang duc, co le mot tram lan ma khong thay vet nut nao. Nhung lan thu mot tram le mot, tang da se vo doi.': 'Khi không có gì có vẻ hiệu quả, hãy nhìn người thợ đá đang đục, có lẽ một trăm lần mà không thấy vết nứt nào. Nhưng lần thứ một trăm lẻ một, tảng đá sẽ vỡ đôi.',
    'Voi thoi quen dua tren ket qua, trong tam la dieu ban muon dat. Voi thoi quen dua tren ban sac, trong tam la nguoi ban muon tro thanh.': 'Với thói quen dựa trên kết quả, trọng tâm là điều bạn muốn đạt. Với thói quen dựa trên bản sắc, trọng tâm là người bạn muốn trở thành.',
    'Van dong khien ban cam thay dang lam duoc viec. Nhung thuc ra ban chi dang chuan bi de lam viec.': 'Vận động khiến bạn cảm thấy đang làm được việc. Nhưng thực ra bạn chỉ đang chuẩn bị để làm việc.',
    'Mot cach tot nhat de xay thoi quen moi la xac dinh thoi quen hien tai ban lam moi ngay roi xep hanh vi moi len tren.': 'Một cách tốt nhất để xây thói quen mới là xác định thói quen hiện tại bạn làm mỗi ngày rồi xếp hành vi mới lên trên.',
    'Giam ma sat lien quan den hanh vi tot. Khi ma sat thap, thoi quen se de dang.': 'Giảm ma sát liên quan đến hành vi tốt. Khi ma sát thấp, thói quen sẽ dễ dàng.',
    'Bi quyet de co ket qua lau dai la khong bao gio ngung cai thien.': 'Bí quyết để có kết quả lâu dài là không bao giờ ngừng cải thiện.',
    'Neu ban muon ket qua tot hon, hay quen viec dat muc tieu. Thay vao do hay tap trung vao he thong.': 'Nếu bạn muốn kết quả tốt hơn, hãy quên việc đặt mục tiêu. Thay vào đó hãy tập trung vào hệ thống.',
    'Chung ta bat chuoc thoi quen cua ba nhom: nguoi than can, so dong va nguoi quyen luc.': 'Chúng ta bắt chước thói quen của ba nhóm: người thân cận, số đông và người quyền lực.',
    'Moi de doa lon nhat cho thanh cong khong phai that bai ma la su nham chan.': 'Mối đe dọa lớn nhất cho thành công không phải thất bại mà là sự nhàm chán.',
    'Chuan hoa truoc khi toi uu. Ban khong the cai thien thoi quen chua ton tai.': 'Chuẩn hóa trước khi tối ưu. Bạn không thể cải thiện thói quen chưa tồn tại.',
    'Nguoi lap ke hoach cu the ve thoi gian va dia diem thuc hien thoi quen moi se de thuc hien hon.': 'Người lập kế hoạch cụ thể về thời gian và địa điểm thực hiện thói quen mới sẽ dễ thực hiện hơn.',
    'Chi khi lam cho nhung dieu co ban trong cuoc song de dang hon, ban moi tao ra khong gian tinh than cho tu duy tu do va sang tao.': 'Chỉ khi làm cho những điều cơ bản trong cuộc sống dễ dàng hơn, bạn mới tạo ra không gian tinh thần cho tư duy tự do và sáng tạo.',
    'Ban cang tu hao ve mot khia canh ban sac, ban cang co dong luc duy tri thoi quen lien quan.': 'Bạn càng tự hào về một khía cạnh bản sắc, bạn càng có động lực duy trì thói quen liên quan.',
    'Thoi quen khong gioi han tu do. Chung tao ra tu do.': 'Thói quen không giới hạn tự do. Chúng tạo ra tự do.',

    # Eckhart Tolle — Power of Now (91-127)
    'Hay nhan ra sau sac rang hien tai la tat ca nhung gi ban co. Hay lay HIEN TAI lam trong tam cuoc song.': 'Hãy nhận ra sâu sắc rằng hiện tại là tất cả những gì bạn có. Hãy lấy HIỆN TẠI làm trọng tâm cuộc sống.',
    'Cuoc song la bay gio. Chua bao gio co luc cuoc doi ban khong phai la bay gio, va cung se khong bao gio.': 'Cuộc sống là bây giờ. Chưa bao giờ có lúc cuộc đời bạn không phải là bây giờ, và cũng sẽ không bao giờ.',
    'Du ban o dau, hay co mat toan ven.': 'Dù bạn ở đâu, hãy có mặt toàn vẹn.',
    'Qua khu khong co quyen luc gi tren khoanh khac hien tai.': 'Quá khứ không có quyền lực gì trên khoảnh khắc hiện tại.',
    'That la giai phong khi nhan ra giong noi trong dau toi khong phai la toi.': 'Thật là giải phóng khi nhận ra giọng nói trong đầu tôi không phải là tôi.',
    'Thoi gian khong quy gia chut nao, vi no la ao giac. Dieu ban cho la quy gia khong phai thoi gian ma la diem duy nhat nam ngoai thoi gian: Hien tai.': 'Thời gian không quý giá chút nào, vì nó là ảo giác. Điều bạn cho là quý giá không phải thời gian mà là điểm duy nhất nằm ngoài thời gian: Hiện tại.',
    'Nguyen nhan chinh cua bat hanh khong bao gio la tinh huong ma la suy nghi cua ban ve no.': 'Nguyên nhân chính của bất hạnh không bao giờ là tình huống mà là suy nghĩ của bạn về nó.',
    'Moi tieu cuc deu do tich tu thoi gian tam ly va phu nhan hien tai.': 'Mọi tiêu cực đều do tích tụ thời gian tâm lý và phủ nhận hiện tại.',
    'Ngay khi ban ton trong khoanh khac hien tai, moi bat hanh va dau tranh tan bien, cuoc song bat dau chay tran niem vui va nhe nhang.': 'Ngay khi bạn tôn trọng khoảnh khắc hiện tại, mọi bất hạnh và đấu tranh tan biến, cuộc sống bắt đầu chảy tràn niềm vui và nhẹ nhàng.',
    'Neu ban on dinh ben trong, ben ngoai se tu vao dung cho.': 'Nếu bạn ổn định bên trong, bên ngoài sẽ tự vào đúng chỗ.',
    'Tri oc la cong cu tuyet voi neu dung dung. Nhung dung sai, no tro nen rat huy diet.': 'Trí óc là công cụ tuyệt vời nếu dùng đúng. Nhưng dùng sai, nó trở nên rất hủy diệt.',
    'Ban luon co the doi pho voi hien tai, nhung khong the doi pho voi thu chi la phong chieu cua tri oc — ban khong the doi pho voi tuong lai.': 'Bạn luôn có thể đối phó với hiện tại, nhưng không thể đối phó với thứ chỉ là phóng chiếu của trí óc — bạn không thể đối phó với tương lai.',
    'Khong co gi tung xay ra trong qua khu; no xay ra trong Hien tai. Khong co gi se xay ra trong tuong lai; no se xay ra trong Hien tai.': 'Không có gì từng xảy ra trong quá khứ; nó xảy ra trong Hiện tại. Không có gì sẽ xảy ra trong tương lai; nó sẽ xảy ra trong Hiện tại.',
    'Dung de the gioi dien ro noi voi ban rang thanh cong la bat cu dieu gi khac ngoai mot khoanh khac hien tai thanh cong.': 'Đừng để thế giới điên rồ nói với bạn rằng thành công là bất cứ điều gì khác ngoài một khoảnh khắc hiện tại thành công.',
    'Bat ky hanh dong nao cung thuong tot hon khong hanh dong, dac biet neu ban da mac ket trong tinh huong bat hanh lau roi.': 'Bất kỳ hành động nào cũng thường tốt hơn không hành động, đặc biệt nếu bạn đã mắc kẹt trong tình huống bất hạnh lâu rồi.',
    'Luon noi co voi hien tai. Buong bo va chap nhan nhung gi dang la. Noi co voi cuoc song — va xem cuoc song bat ngo lam viec cho ban thay vi chong lai ban.': 'Luôn nói có với hiện tại. Buông bỏ và chấp nhận những gì đang là. Nói có với cuộc sống — và xem cuộc sống bất ngờ làm việc cho bạn thay vì chống lại bạn.',
    'Co su khac biet giua hanh phuc va binh yen noi tam khong? Co. Hanh phuc phu thuoc vao dieu kien duoc xem la tich cuc; binh yen noi tam thi khong.': 'Có sự khác biệt giữa hạnh phúc và bình yên nội tâm không? Có. Hạnh phúc phụ thuộc vào điều kiện được xem là tích cực; bình yên nội tâm thì không.',
    'Chap nhan — roi hanh dong. Du hien tai chua dieu gi, hay chap nhan no nhu the ban da chon no.': 'Chấp nhận — rồi hành động. Dù hiện tại chứa điều gì, hãy chấp nhận nó như thể bạn đã chọn nó.',
    'Bat an, lo lang, cang thang, stress — moi dang so hai — deu do qua nhieu tuong lai va khong du hien tai.': 'Bất an, lo lắng, căng thẳng, stress — mọi dạng sợ hãi — đều do quá nhiều tương lai và không đủ hiện tại.',
    'Toi loi, hoi tiec, oan gian, buon ba va moi dang khong tha thu deu do qua nhieu qua khu va khong du hien tai.': 'Tội lỗi, hối tiếc, oán giận, buồn bã và mọi dạng không tha thứ đều do quá nhiều quá khứ và không đủ hiện tại.',
    'Khoanh khac ban nhan ra minh khong o hien tai, ban da o hien tai.': 'Khoảnh khắc bạn nhận ra mình không ở hiện tại, bạn đã ở hiện tại.',
    'Voi ban nga, hien tai hau nhu khong ton tai. Chi qua khu va tuong lai moi duoc xem la quan trong.': 'Với bản ngã, hiện tại hầu như không tồn tại. Chỉ quá khứ và tương lai mới được xem là quan trọng.',
    'Ban tim thay binh yen khong phai bang cach sap xep lai hoan canh, ma bang cach nhan ra minh la ai o tang sau nhat.': 'Bạn tìm thấy bình yên không phải bằng cách sắp xếp lại hoàn cảnh, mà bằng cách nhận ra mình là ai ở tầng sâu nhất.',
    'Khoai lac luon den tu ben ngoai, trong khi niem vui nay sinh tu ben trong.': 'Khoái lạc luôn đến từ bên ngoài, trong khi niềm vui nảy sinh từ bên trong.',
    'Suc manh de tao tuong lai tot hon nam trong hien tai: Ban tao tuong lai tot bang cach tao hien tai tot.': 'Sức mạnh để tạo tương lai tốt hơn nằm trong hiện tại: Bạn tạo tương lai tốt bằng cách tạo hiện tại tốt.',

    # Viktor Frankl — Man's Search for Meaning (116-154)
    'Nguoi co ly do de song co the chiu dung hau het moi cach song.': 'Người có lý do để sống có thể chịu đựng hầu hết mọi cách sống.',
    'Khi khong the thay doi tinh huong, chung ta duoc thach thuc de thay doi chinh minh.': 'Khi không thể thay đổi tình huống, chúng ta được thách thức để thay đổi chính mình.',
    "Moi thu co the bi lay di tu con nguoi tru mot dieu: tu do cuoi cung — quyen chon thai do trong moi hoan canh, quyen chon con duong cua minh.": 'Mọi thứ có thể bị lấy đi từ con người trừ một điều: tự do cuối cùng — quyền chọn thái độ trong mọi hoàn cảnh, quyền chọn con đường của mình.',
    'Giua kich thich va phan ung co mot khoang trong. Trong khoang trong do la quyen lua chon phan ung. Trong phan ung cua ta nam su truong thanh va tu do.': 'Giữa kích thích và phản ứng có một khoảng trống. Trong khoảng trống đó là quyền lựa chọn phản ứng. Trong phản ứng của ta nằm sự trưởng thành và tự do.',
    "Nguoi co 'tai sao' de song co the chiu dung bat ky 'cach nao'.": "Người có 'tại sao' để sống có thể chịu đựng bất kỳ 'cách nào'.",
    'Theo mot cach nao do, dau kho khong con la dau kho khi no tim thay y nghia, nhu y nghia cua su hy sinh.': 'Theo một cách nào đó, đau khổ không còn là đau khổ khi nó tìm thấy ý nghĩa, như ý nghĩa của sự hy sinh.',
    'Dung nham vao thanh cong. Ban cang nham vao no va bien no thanh muc tieu, ban cang de truot.': 'Đừng nhắm vào thành công. Bạn càng nhắm vào nó và biến nó thành mục tiêu, bạn càng dễ trượt.',
    'Dieu gi mang lai anh sang phai chiu dung su thieu dot.': 'Điều gì mang lại ánh sáng phải chịu đựng sự thiêu đốt.',
    'Phan ung bat thuong truoc tinh huong bat thuong la hanh vi binh thuong.': 'Phản ứng bất thường trước tình huống bất thường là hành vi bình thường.',
    'Cuoc song khong bao gio tro nen khong the chiu noi vi hoan canh, ma chi vi thieu y nghia va muc dich.': 'Cuộc sống không bao giờ trở nên không thể chịu nổi vì hoàn cảnh, mà chỉ vì thiếu ý nghĩa và mục đích.',
    'Thanh cong, nhu hanh phuc, khong the theo duoi; no phai tu den, va chi den nhu hieu ung phu cua su cong hien cho muc dich lon hon ban than.': 'Thành công, như hạnh phúc, không thể theo đuổi; nó phải tự đến, và chỉ đến như hiệu ứng phụ của sự cống hiến cho mục đích lớn hơn bản thân.',
    'Su cuu roi cua con nguoi la thong qua tinh yeu va trong tinh yeu.': 'Sự cứu rỗi của con người là thông qua tình yêu và trong tình yêu.',
    'Thach thuc y nghia cuoc song la bieu hien chan thuc nhat cua trang thai lam nguoi.': 'Thách thức ý nghĩa cuộc sống là biểu hiện chân thực nhất của trạng thái làm người.',
    'Khong ai nen phan xet tru khi tu hoi minh trong tinh huong tuong tu lieu co lam giong vay khong.': 'Không ai nên phán xét trừ khi tự hỏi mình trong tình huống tương tự liệu có làm giống vậy không.',
    'Con nguoi khong chi ton tai ma luon quyet dinh su ton tai cua minh se la gi, minh se tro thanh gi vao khoanh khac tiep theo.': 'Con người không chỉ tồn tại mà luôn quyết định sự tồn tại của mình sẽ là gì, mình sẽ trở thành gì vào khoảnh khắc tiếp theo.',
    'Cuoi cung, con nguoi khong nen hoi y nghia cuoc doi la gi, ma phai nhan ra chinh minh la nguoi bi hoi.': 'Cuối cùng, con người không nên hỏi ý nghĩa cuộc đời là gì, mà phải nhận ra chính mình là người bị hỏi.',
    'Hay song nhu the ban dang song lan thu hai va nhu the lan dau ban da hanh dong sai lam nhu ban sap lam bay gio.': 'Hãy sống như thể bạn đang sống lần thứ hai và như thể lần đầu bạn đã hành động sai lầm như bạn sắp làm bây giờ.',
    'Nguoi y thuc duoc trach nhiem voi nguoi dang yeu thuong cho doi minh, hoac voi cong viec dang do, se khong bao gio bo di cuoc doi.': 'Người ý thức được trách nhiệm với người đang yêu thương chờ đợi mình, hoặc với công việc dang dở, sẽ không bao giờ bỏ đi cuộc đời.',
    'Dieu duy nhat ban khong the lay di tu toi la cach toi chon phan ung truoc nhung gi ban lam voi toi.': 'Điều duy nhất bạn không thể lấy đi từ tôi là cách tôi chọn phản ứng trước những gì bạn làm với tôi.',
    'Nhung luc luong ngoai tam kiem soat co the lay di tat ca tru mot dieu: tu do chon cach ban phan ung.': 'Những lực lượng ngoài tầm kiểm soát có thể lấy đi tất cả trừ một điều: tự do chọn cách bạn phản ứng.',
    'Ngay ca nan nhan bat luc trong tinh huong tuyet vong, doi mat so phan khong the thay doi, van co the vuon len tren chinh minh va thay doi ban than.': 'Ngay cả nạn nhân bất lực trong tình huống tuyệt vọng, đối mặt số phận không thể thay đổi, vẫn có thể vươn lên trên chính mình và thay đổi bản thân.',
    'Dieu quan trong khong phai la ta ky vong gi tu cuoc song, ma la cuoc song ky vong gi tu ta.': 'Điều quan trọng không phải là ta kỳ vọng gì từ cuộc sống, mà là cuộc sống kỳ vọng gì từ ta.',
    'Y nghia cua cuoc song la mang lai y nghia cho cuoc song.': 'Ý nghĩa của cuộc sống là mang lại ý nghĩa cho cuộc sống.',
    'Moi nguoi deu bi cuoc doi chat van; va chi co the tra loi cuoc doi bang cach chiu trach nhiem cho cuoc doi minh.': 'Mọi người đều bị cuộc đời chất vấn; và chỉ có thể trả lời cuộc đời bằng cách chịu trách nhiệm cho cuộc đời mình.',
    'Ngay cang nhieu nguoi co phuong tien de song nhung khong co y nghia de song.': 'Ngày càng nhiều người có phương tiện để sống nhưng không có ý nghĩa để sống.',
}

# Apply replacements
for old, new in replacements.items():
    old_pattern = f'vi: "{old}"'
    new_pattern = f'vi: "{new}"'
    if old_pattern in content:
        content = content.replace(old_pattern, new_pattern)
    else:
        print(f"WARNING: Not found: {old[:60]}...")

with open('/Users/chloedreamer/chloe-workspace/src/lib/quotes.ts', 'w', encoding='utf-8') as f:
    f.write(content)

print("Phase 1 done - processed first ~155 quotes")
